name: kk_360
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/tutor.png
    - assets/images/student.png
    - assets/images/admin.png
    - assets/images/login.png
    - assets/images/google.png
    - assets/images/pass.png
    - assets/images/otp.png
    - assets/images/person.png
    - assets/images/maths.png
    - assets/images/female.png
    - assets/images/megaphone.png
    - assets/images/meeting.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
  

