name: kk_360
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  http: ^1.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/tutor.png
    - assets/images/student.png
    - assets/images/admin.png
    - assets/images/login.png
    - assets/images/google.png
    - assets/images/pass.png
    - assets/images/otp.png
    - assets/images/person.png
    - assets/images/maths.png
    - assets/images/female.png
    - assets/images/megaphone.png
    - assets/images/meeting.png
    - assets/images/work.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

# ---------------------------
# Launcher icon configuration
# ---------------------------
flutter_icons:
  android: true
  ios: true
  # I changed this to use 'logo.jpg' since that is in your assets list
  image_path: "assets/images/app_icon.png"

  # This creates the "Circle" icon on Android (Adaptive Icon)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
